/**
 * Compiled-in fallback Google OAuth client for the Drive backup device flow.
 *
 * WHY: hosted users connect Drive from app.nightjar.ca and never see a shell,
 * so an "official" build has to carry a client of its own — otherwise the
 * feature can only ever report "not configured".
 *
 * These values are EMPTY in git on purpose. Official images bake them at
 * Docker build time:
 *
 *   docker build -f apps/node/Dockerfile \
 *     --build-arg NIGHTJAR_GOOGLE_CLIENT_ID=... \
 *     --build-arg NIGHTJAR_GOOGLE_CLIENT_SECRET=... .
 *
 * which runs `apps/node/scripts/bake-oauth.mjs` to rewrite this file. With no
 * build args the file is regenerated byte-identical (both values empty) and
 * the feature keeps reporting "not configured" unless the operator supplies a
 * client via env or config.json.
 *
 * Resolution order per field (see GdriveBackup.credentials): env var, then
 * `backup.gdrive.*` in config.json, then these defaults.
 *
 * On the "secret": for the device-flow ("TVs and Limited Input devices")
 * client type Google states the client secret is not treated as confidential,
 * precisely because it ships inside distributed binaries. It still only ever
 * unlocks a consent screen the user has to approve, and grants the
 * `drive.file` scope alone. Self-hosters who would rather use their own client
 * can — see apps/node/README.md#google-drive-backup.
 */
export const DEFAULT_GOOGLE_OAUTH = {
  clientId: "",
  clientSecret: "",
} as const;
