import {
  REALTIME_BROADCAST_EVENT,
  RealtimeMessage,
  nodeTopic,
  type SnapshotRequest,
  type NodeStatusRequest,
  type TimelineCoverageRequest,
  type TimelineDaysRequest,
  type TimelineExportRequest,
  type WhepOffer,
} from "@nightjar/shared";
import { REALTIME_SUBSCRIBE_STATES, type RealtimeChannel } from "@supabase/supabase-js";
import type { z } from "zod";
import type { BrowserClient } from "@/lib/supabase/client";

/**
 * Promise-based request/reply over the per-node private Realtime channel
 * (topic `node:{nodeId}`, broadcast event "nightjar").
 *
 * Every outgoing request gets a random `requestId`; the node echoes it back in
 * the reply, letting many concurrent requests multiplex a single channel.
 * Incoming payloads are validated with `RealtimeMessage.safeParse`.
 */

export type NodeChannelErrorCode = "timeout" | "channel" | "node_error" | "closed";

export class NodeChannelError extends Error {
  constructor(
    message: string,
    readonly code: NodeChannelErrorCode = "channel",
  ) {
    super(message);
    this.name = "NodeChannelError";
  }
}

/** Reply message types a browser can wait on. */
type ReplyMessage = Extract<
  RealtimeMessage,
  {
    type:
      | "whep_answer"
      | "snapshot_reply"
      | "status_reply"
      | "timeline_days_reply"
      | "timeline_coverage_reply"
      | "timeline_export_reply";
  }
>;

/** Requests a browser can send (requestId is generated by the helper). */
type OutgoingRequest =
  | Omit<z.infer<typeof WhepOffer>, "requestId">
  | Omit<z.infer<typeof SnapshotRequest>, "requestId">
  | Omit<z.infer<typeof NodeStatusRequest>, "requestId">
  | Omit<z.infer<typeof TimelineDaysRequest>, "requestId">
  | Omit<z.infer<typeof TimelineCoverageRequest>, "requestId">
  | Omit<z.infer<typeof TimelineExportRequest>, "requestId">;

interface Pending {
  expect: readonly ReplyMessage["type"][];
  resolve: (msg: ReplyMessage) => void;
  reject: (err: NodeChannelError) => void;
  timer: ReturnType<typeof setTimeout>;
}

export const DEFAULT_REQUEST_TIMEOUT_MS = 10_000;

export class NodeChannel {
  private readonly pending = new Map<string, Pending>();
  private closed = false;

  private constructor(
    readonly nodeId: string,
    private readonly channel: RealtimeChannel,
  ) {}

  /**
   * Authorizes Realtime with the current session token (required for private
   * channels), subscribes to `node:{nodeId}` and resolves once joined.
   */
  static async connect(supabase: BrowserClient, nodeId: string): Promise<NodeChannel> {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) throw new NodeChannelError("You are signed out.", "channel");

    // Private channels require an authorized realtime connection.
    await supabase.realtime.setAuth(token);

    const channel = supabase.channel(nodeTopic(nodeId), {
      config: { private: true, broadcast: { self: false, ack: false } },
    });

    const nodeChannel = new NodeChannel(nodeId, channel);
    channel.on("broadcast", { event: REALTIME_BROADCAST_EVENT }, ({ payload }) => {
      nodeChannel.handleIncoming(payload);
    });

    await new Promise<void>((resolve, reject) => {
      let settled = false;
      channel.subscribe((status, err) => {
        if (settled) return;
        if (status === REALTIME_SUBSCRIBE_STATES.SUBSCRIBED) {
          settled = true;
          resolve();
        } else if (
          status === REALTIME_SUBSCRIBE_STATES.CHANNEL_ERROR ||
          status === REALTIME_SUBSCRIBE_STATES.TIMED_OUT ||
          status === REALTIME_SUBSCRIBE_STATES.CLOSED
        ) {
          settled = true;
          reject(
            new NodeChannelError(
              err?.message ?? `Could not join the node channel (${status.toLowerCase()}).`,
              "channel",
            ),
          );
        }
      });
    });

    return nodeChannel;
  }

  private handleIncoming(payload: unknown): void {
    const parsed = RealtimeMessage.safeParse(payload);
    if (!parsed.success) return;
    const message = parsed.data;

    // Requests from other browsers/the node itself are not for us.
    if (
      message.type === "whep_offer" ||
      message.type === "snapshot_request" ||
      message.type === "status_request" ||
      message.type === "timeline_days_request" ||
      message.type === "timeline_coverage_request" ||
      message.type === "timeline_export_request"
    ) {
      return;
    }

    const pending = this.pending.get(message.requestId);
    if (!pending) return;

    if (message.type === "error") {
      this.pending.delete(message.requestId);
      clearTimeout(pending.timer);
      pending.reject(new NodeChannelError(message.message, "node_error"));
      return;
    }

    if (!pending.expect.includes(message.type)) return;
    this.pending.delete(message.requestId);
    clearTimeout(pending.timer);
    pending.resolve(message);
  }

  /**
   * Sends a request and resolves with the matching reply (same requestId, one
   * of the expected types), or rejects on node error / timeout.
   */
  async request<TType extends ReplyMessage["type"]>(
    message: OutgoingRequest,
    expect: readonly TType[],
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<Extract<ReplyMessage, { type: TType }>> {
    if (this.closed) throw new NodeChannelError("Channel is closed.", "closed");

    const requestId = crypto.randomUUID();
    const payload: RealtimeMessage = { ...message, requestId };

    return new Promise<Extract<ReplyMessage, { type: TType }>>((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(requestId);
        reject(
          new NodeChannelError(
            `The node did not reply within ${Math.round(timeoutMs / 1000)}s.`,
            "timeout",
          ),
        );
      }, timeoutMs);

      this.pending.set(requestId, {
        expect,
        // Safe: handleIncoming only resolves with a message whose type is in `expect`.
        resolve: resolve as unknown as (msg: ReplyMessage) => void,
        reject,
        timer,
      });

      void this.channel
        .send({ type: "broadcast", event: REALTIME_BROADCAST_EVENT, payload })
        .then((status) => {
          if (status !== "ok") {
            const entry = this.pending.get(requestId);
            if (entry) {
              this.pending.delete(requestId);
              clearTimeout(entry.timer);
              reject(new NodeChannelError(`Failed to send request (${status}).`, "channel"));
            }
          }
        })
        .catch((err: unknown) => {
          const entry = this.pending.get(requestId);
          if (entry) {
            this.pending.delete(requestId);
            clearTimeout(entry.timer);
            reject(
              new NodeChannelError(
                err instanceof Error ? err.message : "Failed to send request.",
                "channel",
              ),
            );
          }
        });
    });
  }

  /** Asks the node for a fresh camera snapshot; resolves to a signed image URL. */
  /** Cold camera streams (e.g. Nest via SDM after Google expires a stream
   *  URL) can take 15–25s to deliver a first frame, so snapshots wait longer
   *  than ordinary requests. */
  async requestSnapshot(
    cameraId: string,
    timeoutMs: number = 30_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "snapshot_request", cameraId },
      ["snapshot_reply"],
      timeoutMs,
    );
    return reply.url;
  }

  /** WHEP signaling: sends the browser's SDP offer, resolves with the node's answer SDP. */
  async requestWhepAnswer(
    cameraId: string,
    sdp: string,
    sub = true,
    timeoutMs = 15_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "whep_offer", cameraId, sub, sdp },
      ["whep_answer"],
      timeoutMs,
    );
    return reply.sdp;
  }

  /** Days (node-local YYYY-MM-DD) with 24/7 recordings for a camera, ascending. */
  async requestTimelineDays(
    cameraId: string,
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<string[]> {
    const reply = await this.request(
      { type: "timeline_days_request", cameraId },
      ["timeline_days_reply"],
      timeoutMs,
    );
    return reply.days;
  }

  /** Merged recorded spans (unix ms) for one node-local day. */
  async requestTimelineCoverage(
    cameraId: string,
    day: string,
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<{ startMs: number; endMs: number }[]> {
    const reply = await this.request(
      { type: "timeline_coverage_request", cameraId, day },
      ["timeline_coverage_reply"],
      timeoutMs,
    );
    return reply.spans;
  }

  /** Exports [fromMs, toMs) on the node and resolves to a signed clip URL.
   *  Long default timeout: the node concatenates segments with ffmpeg and
   *  uploads the result before it can reply. */
  async requestTimelineExport(
    cameraId: string,
    fromMs: number,
    toMs: number,
    timeoutMs: number = 60_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "timeline_export_request", cameraId, fromMs, toMs },
      ["timeline_export_reply"],
      timeoutMs,
    );
    return reply.url;
  }

  /** Unsubscribes and rejects any in-flight requests. Safe to call twice. */
  close(): void {
    if (this.closed) return;
    this.closed = true;
    for (const entry of this.pending.values()) {
      clearTimeout(entry.timer);
      entry.reject(new NodeChannelError("Channel is closed.", "closed"));
    }
    this.pending.clear();
    void this.channel.unsubscribe();
  }
}
