import {
  REALTIME_BROADCAST_EVENT,
  RealtimeMessage,
  nodeTopic,
  type GdriveConnectRequest,
  type GdriveDisconnectRequest,
  type GdriveStatusPayload,
  type GdriveStatusRequest,
  type GdriveToggleRequest,
  type SnapshotRequest,
  type NodeStatusRequest,
  type TimelineCoverageRequest,
  type TimelineDaysRequest,
  type TimelineExportRequest,
  type TimelinePreviewRequest,
  type UpdateZonesRequest,
  type WhepOffer,
  type Zone,
} from "@nightjar/shared";
import { REALTIME_SUBSCRIBE_STATES, type RealtimeChannel } from "@supabase/supabase-js";
import type { z } from "zod";
import type { BrowserClient } from "@/lib/supabase/client";

/**
 * Promise-based request/reply over the per-node private Realtime channel
 * (topic `node:{nodeId}`, broadcast event "nightjar").
 *
 * Every outgoing request gets a random `requestId`; the node echoes it back in
 * the reply, letting many concurrent requests multiplex a single channel.
 * Incoming payloads are validated with `RealtimeMessage.safeParse`.
 */

export type NodeChannelErrorCode =
  | "timeout"
  | "channel"
  | "node_error"
  | "closed"
  | "channel_lost";

export class NodeChannelError extends Error {
  constructor(
    message: string,
    readonly code: NodeChannelErrorCode = "channel",
  ) {
    super(message);
    this.name = "NodeChannelError";
  }
}

/** Reply message types a browser can wait on. */
type ReplyMessage = Extract<
  RealtimeMessage,
  {
    type:
      | "whep_answer"
      | "snapshot_reply"
      | "status_reply"
      | "timeline_days_reply"
      | "timeline_coverage_reply"
      | "timeline_preview_reply"
      | "timeline_export_reply"
      | "update_zones_reply"
      | "gdrive_status_reply"
      | "gdrive_connect_reply"
      | "gdrive_toggle_reply"
      | "gdrive_disconnect_reply";
  }
>;

/** Requests a browser can send (requestId is generated by the helper). */
type OutgoingRequest =
  | Omit<z.infer<typeof WhepOffer>, "requestId">
  | Omit<z.infer<typeof SnapshotRequest>, "requestId">
  | Omit<z.infer<typeof NodeStatusRequest>, "requestId">
  | Omit<z.infer<typeof TimelineDaysRequest>, "requestId">
  | Omit<z.infer<typeof TimelineCoverageRequest>, "requestId">
  | Omit<z.infer<typeof TimelinePreviewRequest>, "requestId">
  | Omit<z.infer<typeof TimelineExportRequest>, "requestId">
  | Omit<z.infer<typeof UpdateZonesRequest>, "requestId">
  | Omit<z.infer<typeof GdriveStatusRequest>, "requestId">
  | Omit<z.infer<typeof GdriveConnectRequest>, "requestId">
  | Omit<z.infer<typeof GdriveToggleRequest>, "requestId">
  | Omit<z.infer<typeof GdriveDisconnectRequest>, "requestId">;

interface Pending {
  expect: readonly ReplyMessage["type"][];
  resolve: (msg: ReplyMessage) => void;
  reject: (err: NodeChannelError) => void;
  timer: ReturnType<typeof setTimeout>;
}

export const DEFAULT_REQUEST_TIMEOUT_MS = 10_000;
/** Cap on joining the realtime channel so a wedged socket can't hang forever. */
export const JOIN_TIMEOUT_MS = 15_000;

/**
 * One shared core per node, shared across components: supabase-js returns the
 * SAME underlying realtime channel object for a duplicate topic, and
 * subscribing an already-joined (or errored) channel never fires its status
 * callback — so two independent subscriptions to one topic on a page would
 * hang forever. The core refcounts its holders and only tears the channel
 * down when the last one releases it.
 *
 * `NodeChannel.connect()` hands each caller its own lightweight handle whose
 * `close()` is idempotent PER HANDLE, so a component double-closing its handle
 * can never double-decrement the shared refcount under other components.
 */
const sharedCores = new Map<string, SharedCore>();

class SharedCore {
  refs = 0;
  private channel: RealtimeChannel | null = null;
  /** Single-flight join/rejoin — concurrent callers await the same attempt. */
  private joinPromise: Promise<void> | null = null;
  /** In-flight removeChannel of a dead channel object; joins wait for it so a
   *  stale object can't be handed back by `supabase.channel()`. */
  private removing: Promise<unknown> | null = null;
  private destroyed = false;
  private readonly pending = new Map<string, Pending>();

  constructor(
    private readonly supabase: BrowserClient,
    readonly nodeId: string,
  ) {}

  /** Resolves once the underlying channel is joined. Safe to call repeatedly;
   *  after a post-join loss this transparently builds a fresh channel. */
  ensureJoined(): Promise<void> {
    if (this.destroyed) {
      return Promise.reject(new NodeChannelError("Channel is closed.", "closed"));
    }
    if (this.channel !== null && this.channel.state === "joined") return Promise.resolve();
    this.joinPromise ??= this.join().finally(() => {
      this.joinPromise = null;
    });
    return this.joinPromise;
  }

  private throwIfDestroyed(): void {
    if (this.destroyed) throw new NodeChannelError("Channel is closed.", "closed");
  }

  private makeChannel(): RealtimeChannel {
    return this.supabase.channel(nodeTopic(this.nodeId), {
      config: { private: true, broadcast: { self: false, ack: false } },
    });
  }

  private async join(): Promise<void> {
    // Wait out any in-flight teardown first: until removeChannel completes,
    // supabase.channel() below would return the dying channel object again.
    if (this.removing) {
      await this.removing;
      this.removing = null;
    }
    this.throwIfDestroyed();

    const { data } = await this.supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) throw new NodeChannelError("You are signed out.", "channel");

    // Private channels require an authorized realtime connection.
    await this.supabase.realtime.setAuth(token);
    this.throwIfDestroyed();

    // A failed earlier join leaves its errored channel registered in the
    // client, and supabase.channel() keeps returning that same object — on
    // which subscribe() is a silent no-op. Force a genuinely fresh channel.
    let channel = this.makeChannel();
    for (let attempt = 0; attempt < 2 && channel.state !== "closed"; attempt++) {
      await this.supabase.removeChannel(channel).catch(() => undefined);
      channel = this.makeChannel();
    }
    if (channel.state !== "closed") {
      throw new NodeChannelError("Could not create a fresh node channel.", "channel");
    }

    channel.on("broadcast", { event: REALTIME_BROADCAST_EVENT }, ({ payload }) => {
      this.handleIncoming(payload);
    });
    this.channel = channel;

    try {
      await new Promise<void>((resolve, reject) => {
        let settled = false;
        const timer = setTimeout(() => {
          if (settled) return;
          settled = true;
          reject(
            new NodeChannelError(
              `Joining the node channel timed out after ${Math.round(JOIN_TIMEOUT_MS / 1000)}s.`,
              "channel",
            ),
          );
        }, JOIN_TIMEOUT_MS);
        channel.subscribe((status, err) => {
          if (status === REALTIME_SUBSCRIBE_STATES.SUBSCRIBED) {
            if (!settled) {
              settled = true;
              clearTimeout(timer);
              resolve();
            }
            return;
          }
          if (
            status === REALTIME_SUBSCRIBE_STATES.CHANNEL_ERROR ||
            status === REALTIME_SUBSCRIBE_STATES.TIMED_OUT ||
            status === REALTIME_SUBSCRIBE_STATES.CLOSED
          ) {
            if (!settled) {
              settled = true;
              clearTimeout(timer);
              reject(
                new NodeChannelError(
                  err?.message ?? `Could not join the node channel (${status.toLowerCase()}).`,
                  "channel",
                ),
              );
            } else {
              // The same subscribe callback keeps firing for post-join
              // transitions — this is the persistent connection-loss monitor.
              this.handleChannelLost(channel, status);
            }
          }
        });
      });
      // Released by every holder while the join was in flight — since the
      // destroy path already saw `this.channel`, it initiated removal; just
      // surface the closure to the caller.
      this.throwIfDestroyed();
    } catch (err) {
      if (this.channel === channel) {
        this.channel = null;
        // Leave nothing behind: an errored channel would otherwise linger in
        // the client and poison the next connect attempt for this topic.
        await this.supabase.removeChannel(channel).catch(() => undefined);
      }
      throw err;
    }
  }

  /** Post-join CLOSED / CHANNEL_ERROR / TIMED_OUT: fail fast and reset so the
   *  next request (or connect) transparently builds a fresh channel. Without
   *  this, send() on a dead channel silently falls back to HTTP broadcast and
   *  "succeeds" while replies never arrive. */
  private handleChannelLost(channel: RealtimeChannel, status: string): void {
    if (this.destroyed || this.channel !== channel) return; // stale or intentional teardown
    this.channel = null;
    this.removing = this.supabase.removeChannel(channel).catch(() => undefined);
    this.rejectAll(
      new NodeChannelError(
        `Lost the connection to the node (${status.toLowerCase()}).`,
        "channel_lost",
      ),
    );
  }

  private rejectAll(err: NodeChannelError): void {
    for (const entry of this.pending.values()) {
      clearTimeout(entry.timer);
      entry.reject(err);
    }
    this.pending.clear();
  }

  private handleIncoming(payload: unknown): void {
    const parsed = RealtimeMessage.safeParse(payload);
    if (!parsed.success) return;
    const message = parsed.data;

    // Requests from other browsers/the node itself are not for us.
    if (
      message.type === "whep_offer" ||
      message.type === "snapshot_request" ||
      message.type === "status_request" ||
      message.type === "timeline_days_request" ||
      message.type === "timeline_coverage_request" ||
      message.type === "timeline_preview_request" ||
      message.type === "timeline_export_request" ||
      message.type === "update_zones_request" ||
      message.type === "gdrive_status_request" ||
      message.type === "gdrive_connect_request" ||
      message.type === "gdrive_toggle_request" ||
      message.type === "gdrive_disconnect_request"
    ) {
      return;
    }

    const pending = this.pending.get(message.requestId);
    if (!pending) return;

    if (message.type === "error") {
      this.pending.delete(message.requestId);
      clearTimeout(pending.timer);
      pending.reject(new NodeChannelError(message.message, "node_error"));
      return;
    }

    if (!pending.expect.includes(message.type)) return;
    this.pending.delete(message.requestId);
    clearTimeout(pending.timer);
    pending.resolve(message);
  }

  async request<TType extends ReplyMessage["type"]>(
    message: OutgoingRequest,
    expect: readonly TType[],
    timeoutMs: number,
  ): Promise<Extract<ReplyMessage, { type: TType }>> {
    this.throwIfDestroyed();

    // Self-heal: after a connection loss (or before the first join finishes)
    // rejoin transparently instead of "sending" into a dead channel.
    if (this.channel === null || this.channel.state !== "joined") {
      await this.ensureJoined();
    }
    const channel = this.channel;
    if (channel === null) {
      throw new NodeChannelError("Lost the connection to the node.", "channel_lost");
    }

    const requestId = crypto.randomUUID();
    const payload: RealtimeMessage = { ...message, requestId };

    return new Promise<Extract<ReplyMessage, { type: TType }>>((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(requestId);
        reject(
          new NodeChannelError(
            `The node did not reply within ${Math.round(timeoutMs / 1000)}s.`,
            "timeout",
          ),
        );
      }, timeoutMs);

      this.pending.set(requestId, {
        expect,
        // Safe: handleIncoming only resolves with a message whose type is in `expect`.
        resolve: resolve as unknown as (msg: ReplyMessage) => void,
        reject,
        timer,
      });

      void channel
        .send({ type: "broadcast", event: REALTIME_BROADCAST_EVENT, payload })
        .then((status) => {
          if (status !== "ok") {
            const entry = this.pending.get(requestId);
            if (entry) {
              this.pending.delete(requestId);
              clearTimeout(entry.timer);
              reject(new NodeChannelError(`Failed to send request (${status}).`, "channel"));
            }
          }
        })
        .catch((err: unknown) => {
          const entry = this.pending.get(requestId);
          if (entry) {
            this.pending.delete(requestId);
            clearTimeout(entry.timer);
            reject(
              new NodeChannelError(
                err instanceof Error ? err.message : "Failed to send request.",
                "channel",
              ),
            );
          }
        });
    });
  }

  /** Drops one holder's reference; tears everything down when the last one goes. */
  release(): void {
    this.refs -= 1;
    if (this.refs > 0) return;
    if (sharedCores.get(this.nodeId) === this) sharedCores.delete(this.nodeId);
    this.destroyed = true;
    this.rejectAll(new NodeChannelError("Channel is closed.", "closed"));
    const channel = this.channel;
    this.channel = null;
    if (channel) void this.supabase.removeChannel(channel).catch(() => undefined);
  }
}

/** Strips the envelope from any of the four Drive replies (they share fields). */
function gdrivePayload(
  reply: Extract<
    ReplyMessage,
    {
      type:
        | "gdrive_status_reply"
        | "gdrive_connect_reply"
        | "gdrive_toggle_reply"
        | "gdrive_disconnect_reply";
    }
  >,
): GdriveStatusPayload {
  const { type: _type, requestId: _requestId, ...payload } = reply;
  return payload;
}

/**
 * Per-caller handle around the shared per-node core. Components keep the same
 * API as before — `NodeChannel.connect(...)`, the request helpers, `close()` —
 * but each caller gets its own handle, so `close()` releases this caller's
 * reference exactly once no matter how many times it runs.
 */
export class NodeChannel {
  private released = false;

  private constructor(private readonly core: SharedCore) {}

  get nodeId(): string {
    return this.core.nodeId;
  }

  /**
   * Authorizes Realtime with the current session token (required for private
   * channels), subscribes to `node:{nodeId}` (join capped at 15s) and resolves
   * once joined. Concurrent callers share one core / one underlying channel.
   */
  static async connect(supabase: BrowserClient, nodeId: string): Promise<NodeChannel> {
    let core = sharedCores.get(nodeId);
    if (!core) {
      core = new SharedCore(supabase, nodeId);
      sharedCores.set(nodeId, core);
    }
    core.refs += 1;
    const handle = new NodeChannel(core);
    try {
      await core.ensureJoined();
      return handle;
    } catch (err) {
      handle.close(); // balance the refcount; evicts the core when last out
      throw err;
    }
  }

  /**
   * Sends a request and resolves with the matching reply (same requestId, one
   * of the expected types), or rejects on node error / timeout. If the
   * underlying channel was lost since the last request, it rejoins first.
   */
  async request<TType extends ReplyMessage["type"]>(
    message: OutgoingRequest,
    expect: readonly TType[],
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<Extract<ReplyMessage, { type: TType }>> {
    if (this.released) throw new NodeChannelError("Channel is closed.", "closed");
    return this.core.request(message, expect, timeoutMs);
  }

  /** Asks the node for a fresh camera snapshot; resolves to a signed image URL. */
  /** Cold camera streams (e.g. Nest via SDM after Google expires a stream
   *  URL) can take 15–25s to deliver a first frame, so snapshots wait longer
   *  than ordinary requests. */
  async requestSnapshot(cameraId: string, timeoutMs: number = 30_000): Promise<string> {
    const reply = await this.request(
      { type: "snapshot_request", cameraId },
      ["snapshot_reply"],
      timeoutMs,
    );
    return reply.url;
  }

  /** WHEP signaling: sends the browser's SDP offer, resolves with the node's answer SDP. */
  async requestWhepAnswer(
    cameraId: string,
    sdp: string,
    sub = true,
    timeoutMs = 15_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "whep_offer", cameraId, sub, sdp },
      ["whep_answer"],
      timeoutMs,
    );
    return reply.sdp;
  }

  /** Days (node-local YYYY-MM-DD) with 24/7 recordings for a camera, ascending. */
  async requestTimelineDays(
    cameraId: string,
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<string[]> {
    const reply = await this.request(
      { type: "timeline_days_request", cameraId },
      ["timeline_days_reply"],
      timeoutMs,
    );
    return reply.days;
  }

  /** Merged recorded spans (unix ms) for one node-local day. */
  async requestTimelineCoverage(
    cameraId: string,
    day: string,
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<{ startMs: number; endMs: number }[]> {
    const reply = await this.request(
      { type: "timeline_coverage_request", cameraId, day },
      ["timeline_coverage_reply"],
      timeoutMs,
    );
    return reply.spans;
  }

  /** Single preview frame near atMs (minute-bucketed on the node); resolves
   *  to a short-TTL signed JPEG URL. Cold extractions run ffmpeg first. */
  async requestTimelinePreview(
    cameraId: string,
    atMs: number,
    timeoutMs: number = 15_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "timeline_preview_request", cameraId, atMs },
      ["timeline_preview_reply"],
      timeoutMs,
    );
    return reply.url;
  }

  /** Exports [fromMs, toMs) on the node and resolves to a signed clip URL.
   *  Long default timeout: the node concatenates segments with ffmpeg and
   *  uploads the result before it can reply. */
  async requestTimelineExport(
    cameraId: string,
    fromMs: number,
    toMs: number,
    timeoutMs: number = 60_000,
  ): Promise<string> {
    const reply = await this.request(
      { type: "timeline_export_request", cameraId, fromMs, toMs },
      ["timeline_export_reply"],
      timeoutMs,
    );
    return reply.url;
  }

  /** Replaces a camera's activity zones on the node; resolves once persisted
   *  (the node also re-syncs the camera row to the cloud). */
  async requestUpdateZones(
    cameraId: string,
    zones: Zone[],
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<void> {
    await this.request(
      { type: "update_zones_request", cameraId, zones },
      ["update_zones_reply"],
      timeoutMs,
    );
  }

  /* ---------- Google Drive backup ----------
   *
   * The node keeps its OAuth tokens on disk and only ever relays display state
   * plus the short device-flow code, which is useless until the signed-in user
   * approves it at google.com/device. Nothing here carries a credential.
   */

  /** Current Drive-backup state of the node (also the connect-flow poll). */
  async requestGdriveStatus(
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<GdriveStatusPayload> {
    return gdrivePayload(
      await this.request({ type: "gdrive_status_request" }, ["gdrive_status_reply"], timeoutMs),
    );
  }

  /** Starts the device flow on the node; resolves with the code to display.
   *  Longer timeout: the node has to reach Google before it can answer. */
  async requestGdriveConnect(timeoutMs = 20_000): Promise<GdriveStatusPayload> {
    return gdrivePayload(
      await this.request({ type: "gdrive_connect_request" }, ["gdrive_connect_reply"], timeoutMs),
    );
  }

  /** Flips either backup switch on the node; omitted fields are left alone. */
  async requestGdriveToggle(
    patch: { enabled?: boolean; shareLinks?: boolean },
    timeoutMs: number = DEFAULT_REQUEST_TIMEOUT_MS,
  ): Promise<GdriveStatusPayload> {
    return gdrivePayload(
      await this.request(
        { type: "gdrive_toggle_request", ...patch },
        ["gdrive_toggle_reply"],
        timeoutMs,
      ),
    );
  }

  /** Revokes the grant at Google and deletes the node's token file. */
  async requestGdriveDisconnect(timeoutMs = 20_000): Promise<GdriveStatusPayload> {
    return gdrivePayload(
      await this.request(
        { type: "gdrive_disconnect_request" },
        ["gdrive_disconnect_reply"],
        timeoutMs,
      ),
    );
  }

  /** Releases this handle's reference — idempotent per handle. The underlying
   *  channel is only torn down when the last holder on the page lets go. */
  close(): void {
    if (this.released) return;
    this.released = true;
    this.core.release();
  }
}
