import { chmodSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  DEFAULT_STUN_SERVERS,
  GO2RTC_RTSP_PORT,
  go2rtcStreamName,
  type CameraConfig,
  type NodeConfig,
} from "@nightjar/shared";
import type { ConfigStore } from "../config/store.js";
import type { Logger } from "../log.js";
import type { NestStreamParams } from "../nest/sdm.js";

/**
 * Keeps go2rtc's config in sync with the Nightjar camera list.
 *
 * go2rtc itself runs as a sibling container (see docker/docker-compose.yml);
 * this "supervisor" renders ${GO2RTC_CONFIG_DIR}/go2rtc.yaml on every config
 * change and pokes go2rtc's /api/restart to pick it up.
 *
 * The yaml is emitted by a tiny hand-rolled serializer: the structure is fixed
 * and every dynamic scalar is JSON-quoted (valid YAML double-quoted scalars),
 * so no yaml dependency is needed.
 *
 * Nest cameras render as go2rtc's native `nest:` source, which embeds the
 * node's SDM OAuth client secret and refresh token — since that made the file
 * secret-bearing, it is always written with mode 0600.
 */
export class Go2rtcSupervisor {
  private readonly configDir: string;
  private unsubscribe: (() => void) | null = null;
  /** Camera ids already warned about (nest camera without a connected account). */
  private readonly warnedSkipped = new Set<string>();

  constructor(
    private readonly store: ConfigStore,
    private readonly log: Logger,
    configDir: string = process.env.GO2RTC_CONFIG_DIR ?? "/go2rtc-config",
    /** Provider for the Nest SDM params `nest:` sources need; null while the
     *  Nest account is not connected (those cameras are then skipped). */
    private readonly nestParams: () => NestStreamParams | null = () => null,
  ) {
    this.configDir = configDir;
  }

  apiUrl(): string {
    return this.store.get().go2rtc.apiUrl.replace(/\/+$/, "");
  }

  async start(): Promise<void> {
    await this.sync();
    this.unsubscribe = this.store.onChange(() => {
      void this.sync();
    });
  }

  stop(): void {
    this.unsubscribe?.();
    this.unsubscribe = null;
  }

  /** Re-render outside a config change (e.g. Nest connect/disconnect). */
  async resync(): Promise<void> {
    await this.sync();
  }

  /** go2rtc source line for a camera's main stream, or null to skip it. */
  private renderSource(camera: CameraConfig): string | null {
    if (camera.source === "nest") {
      const params = this.nestParams();
      if (!params || !camera.nest) {
        if (!this.warnedSkipped.has(camera.id)) {
          this.warnedSkipped.add(camera.id);
          this.log.warn(
            `nest camera "${camera.name}" (${camera.id}) skipped — Nest account not connected`,
          );
        }
        return null;
      }
      this.warnedSkipped.delete(camera.id);
      const query = new URLSearchParams({
        client_id: params.clientId,
        client_secret: params.clientSecret,
        refresh_token: params.refreshToken,
        project_id: params.projectId,
        device_id: camera.nest.deviceId,
      });
      return `nest:?${query.toString()}`;
    }
    return camera.rtspUrl ?? null;
  }

  private render(config: NodeConfig): string {
    const lines: string[] = [];
    lines.push("# Generated by Nightjar — do not edit; overwritten on config change.");
    lines.push("api:");
    lines.push(`  listen: ":1984"`);
    lines.push("rtsp:");
    // The node re-consumes nest streams over this RTSP restream (recorder +
    // motion detection); go2rtc's default, made explicit.
    lines.push(`  listen: ":${GO2RTC_RTSP_PORT}"`);
    lines.push("webrtc:");
    lines.push(`  listen: ":8555"`);
    lines.push("  ice_servers:");
    lines.push("    - urls:");
    for (const server of DEFAULT_STUN_SERVERS) {
      lines.push(`        - ${JSON.stringify(server)}`);
    }
    const streams: string[] = [];
    for (const camera of config.cameras) {
      if (!camera.enabled) continue;
      const main = this.renderSource(camera);
      if (main === null) continue;
      const sub = camera.source === "rtsp" ? (camera.rtspSubUrl ?? main) : main;
      streams.push(`  ${JSON.stringify(go2rtcStreamName(camera.id))}: ${JSON.stringify(main)}`);
      streams.push(`  ${JSON.stringify(go2rtcStreamName(camera.id, true))}: ${JSON.stringify(sub)}`);
    }
    if (streams.length === 0) {
      lines.push("streams: {}");
    } else {
      lines.push("streams:");
      lines.push(...streams);
    }
    return `${lines.join("\n")}\n`;
  }

  /** Render the yaml; if it changed on disk, write atomically and ask go2rtc to restart. */
  private async sync(): Promise<void> {
    const file = path.join(this.configDir, "go2rtc.yaml");
    const next = this.render(this.store.get());

    let current: string | null = null;
    try {
      current = readFileSync(file, "utf8");
    } catch {
      // missing file — will write below
    }
    if (current === next) {
      // Content unchanged, but tighten perms on files written by older builds.
      try {
        chmodSync(file, 0o600);
      } catch {
        // best effort
      }
      return;
    }

    mkdirSync(this.configDir, { recursive: true });
    const tmp = `${file}.tmp`;
    // 0600: the file may embed camera credentials and Nest OAuth secrets.
    writeFileSync(tmp, next, { encoding: "utf8", mode: 0o600 });
    renameSync(tmp, file);
    this.log.info(`wrote ${file}`);

    try {
      await fetch(`${this.apiUrl()}/api/restart`, { method: "POST" });
      this.log.info("asked go2rtc to restart");
    } catch {
      this.log.warn("go2rtc restart request failed (is go2rtc running?)");
    }
  }

  async health(): Promise<boolean> {
    try {
      const res = await fetch(`${this.apiUrl()}/api`);
      return res.ok;
    } catch {
      return false;
    }
  }

  /** Configured stream map from go2rtc, or null when go2rtc is unreachable. */
  async streams(): Promise<Record<string, unknown> | null> {
    try {
      const res = await fetch(`${this.apiUrl()}/api/streams`);
      if (!res.ok) return null;
      const data: unknown = await res.json();
      if (data !== null && typeof data === "object" && !Array.isArray(data)) {
        return data as Record<string, unknown>;
      }
      return null;
    } catch {
      return null;
    }
  }
}
