import { chmodSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  DEFAULT_STUN_SERVERS,
  GO2RTC_RTSP_PORT,
  go2rtcStreamName,
  type CameraConfig,
  type NodeConfig,
} from "@nightjar/shared";
import type { ConfigStore } from "../config/store.js";
import type { Logger } from "../log.js";
import type { NestStreamParams } from "../nest/sdm.js";

/**
 * Keeps go2rtc's config in sync with the Nightjar camera list.
 *
 * go2rtc itself runs as a sibling container (see docker/docker-compose.yml);
 * this "supervisor" renders ${GO2RTC_CONFIG_DIR}/go2rtc.yaml on every config
 * change and pokes go2rtc's /api/restart to pick it up.
 *
 * The yaml is emitted by a tiny hand-rolled serializer: the structure is fixed
 * and every dynamic scalar is JSON-quoted (valid YAML double-quoted scalars),
 * so no yaml dependency is needed.
 *
 * Nest cameras render as go2rtc's native `nest:` source, which embeds the
 * node's SDM OAuth client secret and refresh token — since that made the file
 * secret-bearing, it is always written with mode 0600.
 */
/** All go2rtc API fetches time out after this — a hung go2rtc must not hang us. */
const FETCH_TIMEOUT_MS = 5_000;
const RESTART_RETRY_MS = 15_000;
const RESTART_RETRY_MAX = 20;

export class Go2rtcSupervisor {
  private readonly configDir: string;
  private unsubscribe: (() => void) | null = null;
  private stopping = false;
  /** True while the restart-poke retry loop is running (never stack a second). */
  private restartRetryActive = false;
  /** Camera ids already warned about (nest camera without a connected account). */
  private readonly warnedSkipped = new Set<string>();

  constructor(
    private readonly store: ConfigStore,
    private readonly log: Logger,
    configDir: string = process.env.GO2RTC_CONFIG_DIR ?? "/go2rtc-config",
    /** Provider for the Nest SDM params `nest:` sources need; null while the
     *  Nest account is not connected (those cameras are then skipped). */
    private readonly nestParams: () => NestStreamParams | null = () => null,
    /** Node-managed SDM stream URL for a camera, when one has been acquired.
     *  Preferred over go2rtc's own `nest:` source — see nest/streams.ts. */
    private readonly nestStreamUrl: (cameraId: string) => string | null = () => null,
  ) {
    this.configDir = configDir;
  }

  apiUrl(): string {
    return this.store.get().go2rtc.apiUrl.replace(/\/+$/, "");
  }

  async start(): Promise<void> {
    await this.sync();
    this.unsubscribe = this.store.onChange(() => {
      void this.sync();
    });
  }

  stop(): void {
    this.stopping = true;
    this.unsubscribe?.();
    this.unsubscribe = null;
  }

  /** Re-render outside a config change (e.g. Nest connect/disconnect). */
  async resync(): Promise<void> {
    await this.sync();
  }

  /** go2rtc source line for a camera's main stream, or null to skip it. */
  private renderSource(camera: CameraConfig): string | null {
    if (camera.source === "nest") {
      // Preferred path: the node owns this stream's lifetime and keeps it
      // extended, so go2rtc just consumes an RTSP URL and never calls SDM.
      // That removes go2rtc's buggy renewal timer and its habit of minting a
      // fresh stream on every reconnect, which is what exhausted the quota.
      const managed = this.nestStreamUrl(camera.id);
      if (managed) {
        this.warnedSkipped.delete(camera.id);
        return managed;
      }
      const params = this.nestParams();
      if (!params || !camera.nest) {
        if (!this.warnedSkipped.has(camera.id)) {
          this.warnedSkipped.add(camera.id);
          this.log.warn(
            `nest camera "${camera.name}" (${camera.id}) skipped — Nest account not connected`,
          );
        }
        return null;
      }
      this.warnedSkipped.delete(camera.id);
      const query = new URLSearchParams({
        client_id: params.clientId,
        client_secret: params.clientSecret,
        refresh_token: params.refreshToken,
        project_id: params.projectId,
        device_id: camera.nest.deviceId,
      });
      // go2rtc defaults to WEB_RTC; RTSP-generation cameras must say so.
      if (camera.nest.protocols.length > 0) {
        query.set("protocols", camera.nest.protocols.join(","));
      }
      return `nest:?${query.toString()}`;
    }
    return camera.rtspUrl ?? null;
  }

  private render(config: NodeConfig): string {
    const lines: string[] = [];
    lines.push("# Generated by Nightjar — do not edit; overwritten on config change.");
    lines.push("api:");
    lines.push(`  listen: ":1984"`);
    lines.push("rtsp:");
    // The node re-consumes nest streams over this RTSP restream (recorder +
    // motion detection); go2rtc's default, made explicit.
    lines.push(`  listen: ":${GO2RTC_RTSP_PORT}"`);
    lines.push("webrtc:");
    lines.push(`  listen: ":8555"`);
    lines.push("  ice_servers:");
    lines.push("    - urls:");
    for (const server of DEFAULT_STUN_SERVERS) {
      lines.push(`        - ${JSON.stringify(server)}`);
    }
    const streams: string[] = [];
    /**
     * Emit one stream. With `withOpus`, a secondary `ffmpeg:{name}#audio=opus`
     * source is added: WebRTC cannot carry the cameras' AAC audio, so go2rtc
     * lazily spawns ffmpeg (loopback via its own RTSP restream of this same
     * stream) to transcode audio to Opus for WebRTC viewers. Plain RTSP
     * consumers (recorder / motion detection) are unaffected — go2rtc serves
     * them the first matching codecs, i.e. the primary source's original
     * H264+AAC, so recordings keep AAC (verified against go2rtc 1.9.x: the
     * restream ffprobes as aac while the WebRTC answer offers opus).
     */
    const pushStream = (name: string, source: string, withOpus: boolean): void => {
      if (!withOpus) {
        streams.push(`  ${JSON.stringify(name)}: ${JSON.stringify(source)}`);
        return;
      }
      streams.push(`  ${JSON.stringify(name)}:`);
      streams.push(`    - ${JSON.stringify(source)}`);
      streams.push(`    - ${JSON.stringify(`ffmpeg:${name}#audio=opus`)}`);
    };
    for (const camera of config.cameras) {
      if (!camera.enabled) continue;
      const main = this.renderSource(camera);
      if (main === null) continue;
      // Nest cameras must NOT open a second SDM session for the sub stream —
      // Google rate-limits stream generation (429s with 5 cams x 2 streams).
      // The sub consumes go2rtc's own restream of main: one Google session
      // per camera, shared by recording, motion, and remote view.
      const sub =
        camera.source === "rtsp"
          ? (camera.rtspSubUrl ?? main)
          : `rtsp://127.0.0.1:${GO2RTC_RTSP_PORT}/${go2rtcStreamName(camera.id)}`;
      // Skip the opus transcode only when the camera is known to have no
      // audio (hasAudio === false); unknown (older configs) gets it too —
      // a stream without audio degrades to an inactive audio m-line.
      // Nest cameras get exactly ONE stream with ONE source. Every extra
      // source is another thing go2rtc can decide to start, and every start
      // asks Google to mint a new SDM stream against a per-minute project
      // quota — the fan-out (main + _sub + two opus loopbacks per camera) was
      // enough to keep that quota permanently saturated, which stopped
      // recording entirely. The cost is live-view audio on Nest cameras:
      // their AAC cannot ride WebRTC without the opus transcode. Recording
      // keeps its original audio either way.
      if (camera.source === "nest") {
        pushStream(go2rtcStreamName(camera.id), main, false);
        continue;
      }
      const withOpus = camera.capabilities.hasAudio !== false;
      pushStream(go2rtcStreamName(camera.id), main, withOpus);
      pushStream(go2rtcStreamName(camera.id, true), sub, withOpus);
    }
    if (streams.length === 0) {
      lines.push("streams: {}");
    } else {
      lines.push("streams:");
      lines.push(...streams);
    }
    return `${lines.join("\n")}\n`;
  }

  /**
   * Rewrite go2rtc.yaml without restarting go2rtc.
   *
   * For changes a running go2rtc does not need to see immediately — currently
   * Nest stream-token rotation. The token in an already-established RTSP
   * session is irrelevant (it only authenticates the initial DESCRIBE), so
   * restarting would tear down five healthy captures to apply something that
   * changes nothing. The file still has to be current, because a go2rtc that
   * restarts for any other reason reads it: renewal runs well inside the
   * token's lifetime, so what is on disk is always still valid.
   */
  async refreshConfig(): Promise<void> {
    await this.sync(false);
  }

  /** Render the yaml; if it changed on disk, write atomically and ask go2rtc to restart. */
  private async sync(restart = true): Promise<void> {
    const file = path.join(this.configDir, "go2rtc.yaml");
    const next = this.render(this.store.get());

    let current: string | null = null;
    try {
      current = readFileSync(file, "utf8");
    } catch {
      // missing file — will write below
    }
    if (current === next) {
      // Content unchanged, but tighten perms on files written by older builds.
      try {
        chmodSync(file, 0o600);
      } catch {
        // best effort
      }
      return;
    }

    mkdirSync(this.configDir, { recursive: true });
    const tmp = `${file}.tmp`;
    // 0600: the file may embed camera credentials and Nest OAuth secrets.
    writeFileSync(tmp, next, { encoding: "utf8", mode: 0o600 });
    renameSync(tmp, file);
    this.log.info(`wrote ${file}`);

    if (!restart) return;
    if (!(await this.pokeRestart())) {
      this.log.warn("go2rtc restart request failed (is go2rtc running?) — will retry");
      this.retryRestartPoke();
    }
  }

  /** POST /api/restart once; true when the request went through. */
  private async pokeRestart(): Promise<boolean> {
    try {
      await fetch(`${this.apiUrl()}/api/restart`, {
        method: "POST",
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      this.log.info("asked go2rtc to restart");
      return true;
    } catch {
      return false;
    }
  }

  /**
   * A failed restart poke means go2rtc never picked up the yaml we just wrote
   * — retry every 15s (max 20 tries) until go2rtc is healthy, then poke once.
   * Only one retry loop runs at a time; a fresh sync that pokes successfully
   * makes the pending loop's extra poke harmless (restart on same config).
   */
  private retryRestartPoke(): void {
    if (this.restartRetryActive) return;
    this.restartRetryActive = true;
    void (async () => {
      try {
        for (let attempt = 0; attempt < RESTART_RETRY_MAX && !this.stopping; attempt++) {
          await new Promise((resolve) => setTimeout(resolve, RESTART_RETRY_MS).unref());
          if (this.stopping) return;
          if (!(await this.health())) continue;
          if (await this.pokeRestart()) return;
        }
        if (!this.stopping) {
          this.log.warn("go2rtc restart poke abandoned — go2rtc never became healthy");
        }
      } finally {
        this.restartRetryActive = false;
      }
    })();
  }

  async health(): Promise<boolean> {
    try {
      const res = await fetch(`${this.apiUrl()}/api`, {
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  /** Configured stream map from go2rtc, or null when go2rtc is unreachable. */
  async streams(): Promise<Record<string, unknown> | null> {
    try {
      const res = await fetch(`${this.apiUrl()}/api/streams`, {
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      });
      if (!res.ok) return null;
      const data: unknown = await res.json();
      if (data !== null && typeof data === "object" && !Array.isArray(data)) {
        return data as Record<string, unknown>;
      }
      return null;
    } catch {
      return null;
    }
  }
}
