import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DEFAULT_STUN_SERVERS, go2rtcStreamName, type NodeConfig } from "@nightjar/shared";
import type { ConfigStore } from "../config/store.js";
import type { Logger } from "../log.js";

/**
 * Keeps go2rtc's config in sync with the Nightjar camera list.
 *
 * go2rtc itself runs as a sibling container (see docker/docker-compose.yml);
 * this "supervisor" renders ${GO2RTC_CONFIG_DIR}/go2rtc.yaml on every config
 * change and pokes go2rtc's /api/restart to pick it up.
 *
 * The yaml is emitted by a tiny hand-rolled serializer: the structure is fixed
 * and every dynamic scalar is JSON-quoted (valid YAML double-quoted scalars),
 * so no yaml dependency is needed.
 */
export class Go2rtcSupervisor {
  private readonly configDir: string;
  private unsubscribe: (() => void) | null = null;

  constructor(
    private readonly store: ConfigStore,
    private readonly log: Logger,
    configDir: string = process.env.GO2RTC_CONFIG_DIR ?? "/go2rtc-config",
  ) {
    this.configDir = configDir;
  }

  apiUrl(): string {
    return this.store.get().go2rtc.apiUrl.replace(/\/+$/, "");
  }

  async start(): Promise<void> {
    await this.sync();
    this.unsubscribe = this.store.onChange(() => {
      void this.sync();
    });
  }

  stop(): void {
    this.unsubscribe?.();
    this.unsubscribe = null;
  }

  private render(config: NodeConfig): string {
    const lines: string[] = [];
    lines.push("# Generated by Nightjar — do not edit; overwritten on config change.");
    lines.push("api:");
    lines.push(`  listen: ":1984"`);
    lines.push("webrtc:");
    lines.push(`  listen: ":8555"`);
    lines.push("  ice_servers:");
    lines.push("    - urls:");
    for (const server of DEFAULT_STUN_SERVERS) {
      lines.push(`        - ${JSON.stringify(server)}`);
    }
    const cameras = config.cameras.filter((c) => c.enabled);
    if (cameras.length === 0) {
      lines.push("streams: {}");
    } else {
      lines.push("streams:");
      for (const camera of cameras) {
        lines.push(`  ${JSON.stringify(go2rtcStreamName(camera.id))}: ${JSON.stringify(camera.rtspUrl)}`);
        lines.push(
          `  ${JSON.stringify(go2rtcStreamName(camera.id, true))}: ${JSON.stringify(camera.rtspSubUrl ?? camera.rtspUrl)}`,
        );
      }
    }
    return `${lines.join("\n")}\n`;
  }

  /** Render the yaml; if it changed on disk, write atomically and ask go2rtc to restart. */
  private async sync(): Promise<void> {
    const file = path.join(this.configDir, "go2rtc.yaml");
    const next = this.render(this.store.get());

    let current: string | null = null;
    try {
      current = readFileSync(file, "utf8");
    } catch {
      // missing file — will write below
    }
    if (current === next) return;

    mkdirSync(this.configDir, { recursive: true });
    const tmp = `${file}.tmp`;
    writeFileSync(tmp, next, "utf8");
    renameSync(tmp, file);
    this.log.info(`wrote ${file}`);

    try {
      await fetch(`${this.apiUrl()}/api/restart`, { method: "POST" });
      this.log.info("asked go2rtc to restart");
    } catch {
      this.log.warn("go2rtc restart request failed (is go2rtc running?)");
    }
  }

  async health(): Promise<boolean> {
    try {
      const res = await fetch(`${this.apiUrl()}/api`);
      return res.ok;
    } catch {
      return false;
    }
  }

  /** Configured stream map from go2rtc, or null when go2rtc is unreachable. */
  async streams(): Promise<Record<string, unknown> | null> {
    try {
      const res = await fetch(`${this.apiUrl()}/api/streams`);
      if (!res.ok) return null;
      const data: unknown = await res.json();
      if (data !== null && typeof data === "object" && !Array.isArray(data)) {
        return data as Record<string, unknown>;
      }
      return null;
    } catch {
      return null;
    }
  }
}
